FROM python:3.13-slim

RUN apt-get update -yqq && apt-get install -yqq curl

COPY --from=ghcr.io/astral-sh/uv:0.9 /uv /bin/uv

# Set working directory
WORKDIR /app

COPY pyproject.toml uv.lock /app/

ENV UV_PROJECT_ENVIRONMENT=/usr/local
RUN uv sync --frozen --no-dev

COPY docker-entrypoint.sh /app/
RUN chmod +x /app/docker-entrypoint.sh

# Copy data to /app
COPY backend/ ./backend
COPY iot_devices/ ./iot_devices

# Expose backend API port
EXPOSE 8000

CMD ["/app/docker-entrypoint.sh"]