# Generated by Django 6.0.4 on 2026-04-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MQTTClientStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("client_type", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="unknown", max_length=50)),
                ("last_seen", models.DateTimeField(auto_now=True, db_index=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("total_packets", models.IntegerField(default=0)),
                ("total_errors", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "MQTT Client Status",
                "verbose_name_plural": "MQTT Client Statuses",
                "ordering": ["-last_seen"],
            },
        ),
    ]
