# Mosquitto Configuration File for easycon
# This configuration is used for local development and testing

# Network settings
listener 1883
protocol mqtt
allow_anonymous true  # Allow anonymous connections for development

# Using the same self-signed certificate for both certfile and cafile
cafile ./iot_devices/mqtt/cert/server.crt
certfile ./iot_devices/mqtt/cert/server.crt
keyfile ./iot_devices/mqtt/cert/server.key

# Security TODO in production
# For production, use:
# allow_anonymous false
# password_file /path/to/password_file
# acl_file /path/to/acl_file

# Persistence
persistence false

# Logging
log_dest stdout
log_type all
connection_messages true
log_timestamp true

# Message size limits
message_size_limit 0

# Keepalive settings
max_keepalive 65535

# Connection limits
max_connections -1
